Repository SWYP-6-6/6-fe, pull requests merged in 2024-10, with the labels that each got.

#22 체크리스트 픽드백 적용 및 저장소 관련 페이지들 추가
  .eslintrc.json
  package-lock.json
  package.json
  public/svgs/add-icon-2.svg
  src/app/main/page.tsx
  src/app/myfamily/checklist/CheckListPage.module.scss
  src/app/myfamily/checklist/page.tsx
  src/app/myfamily/page.tsx
  src/app/myfamily/storage/StoragePage.module.scss
  src/app/myfamily/storage/[id]/travel-review-form/TravelReviewFormPage.module.scss
  src/app/myfamily/storage/[id]/travel-review-form/page.tsx
  src/app/myfamily/storage/[id]/travel-review/TravelReviewPage.module.scss
  src/app/myfamily/storage/[id]/travel-review/page.tsx
  src/app/myfamily/storage/add/StorageAdd.module.scss
  src/app/myfamily/storage/add/page.tsx
  src/app/myfamily/storage/page.tsx
  src/components/common/DatePicker.tsx
  src/components/myfamily/Calendar.tsx
  src/components/myfamily/TravelRecord.module.scss
  src/components/myfamily/TravelRecord.tsx
Labels: design, feat, refactor

#27 메인페이지 디자인 업데이트 footer 컴포넌트 생성
  .env
  public/svgs/footer-group.svg
  public/svgs/footer-home.svg
  public/svgs/footer-individual.svg
  public/svgs/login-center.svg
  public/svgs/login-center1.svg
  public/svgs/login-center2.svg
  public/svgs/login-center3.svg
  public/svgs/login-center4.svg
  src/app/main/[mainid]/page.tsx
  src/app/main/main.module.scss
  src/app/signin/page.tsx
  src/app/signin/signin.module.scss
  src/components/common/Footer.module.scss
  src/components/common/Footer.tsx
  src/components/common/MainComment.module.scss
  src/components/common/MainComment.tsx
Labels: design, feat

#29 profile 페이지 ui 구현
  src/app/profile/ProfilePage.module.scss
  src/app/profile/page.tsx
  src/components/profile/ProfileToggles.module.scss
  src/components/profile/ProfileToggles.tsx
  src/styles/mixins/_text-style.scss
  src/styles/variables/_typography.scss
Labels: design, feat, refactor

#35 fix: 리다이렉트 주소 변경 및 폼 제출시 버튼 비활성화 추가
  src/app/api/auth/route.ts
  src/app/mainform/MainFormPage.module.scss
  src/app/mainform/MainFormPage.tsx
Labels: bugFix, refactor

#42 myprofile 페이지 기능구현 및 오류 해결
  .eslintrc.json
  src/app/api/api.ts
  src/app/main/[id]/mainId.module.scss
  src/app/page.tsx
  src/app/profile/ProfilePage.module.scss
  src/app/profile/ProfilePageClient.tsx
  src/app/profile/page.tsx
  src/components/common/CommonButton.tsx
  src/components/common/Header.tsx
  src/components/main.module.scss
  src/components/mainClient.tsx
Labels: feat, bugFix, refactor

#47 Footer 적용
  public/svgs/footer-group.svg
  public/svgs/footer-home.svg
  public/svgs/footer-individual.svg
  src/app/myfamily/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/components/common/Footer.module.scss
  src/components/common/Footer.tsx
  src/components/main.module.scss
Labels: feat, refactor

#54 API 연동
  src/app/api/api.ts
  src/app/api/login/route.ts
  src/app/group/page.tsx
  src/app/myfamily/calendar/page.tsx
  src/app/signin/page.tsx
  src/components/anniversary/SettingForm.tsx
  src/components/common/Header.tsx
  src/components/group/profileImg.tsx
  src/utils/dateBetween.ts
  tsconfig.json
Labels: api

#70 기념일 설정 기능 , 가족구성원 페이지 구현
  src/app/anniversary/layout.tsx
  src/app/api/api.ts
  src/app/group/anniversary/AnniversarySettingPage.module.scss
  src/app/group/anniversary/page.tsx
  src/app/group/anniversary/setting/page.tsx
  src/app/group/member/MemberPage.module.scss
  src/app/group/member/page.tsx
  src/app/group/page.tsx
  src/components/group/anniversary/AnniversaySwipeableListItem.module.scss
  src/components/group/anniversary/AnniversaySwipeableListItem.tsx
  src/components/group/anniversary/setting/DataPick.module.scss
  src/components/group/anniversary/setting/DataPick.tsx
  src/components/group/anniversary/setting/SettingForm.module.scss
  src/components/group/anniversary/setting/SettingForm.tsx
  src/types/types.ts
Labels: feat, refactor

#74 배경색 및 파비콘 및 SEO 설정
  public/svgs/favicon.svg
  public/svgs/preview.svg
  src/app/layout.module.scss
  src/app/layout.tsx
  src/app/profile/ProfilePage.module.scss
  src/components/main.module.scss
  src/styles/base/_globals.scss
Labels: design, refactor

#85 fix: 작성 후 버튼 클릭 시 중첩 post 방지
  src/app/mainform/MainFormPage.module.scss
  src/app/mainform/MainFormPage.tsx
  src/app/myfamily/calendar/page.tsx
Labels: bugFix

#87 기념일 api 데이터 구조 변경 적용 및 리팩토링
  src/app/api/api.ts
  src/app/group/anniversary/AnniversarySettingPage.module.scss
  src/app/group/anniversary/page.tsx
  src/app/group/member/page.tsx
  src/app/group/page.tsx
  src/app/myfamily/storage/SwipeableListItem.tsx
  src/app/myfamily/storage/[id]/travel-review-form/page.tsx
  src/app/myfamily/storage/[id]/travel-review/page.tsx
  src/app/myfamily/storage/page.tsx
  src/components/group/anniversary/AnniversaySwipeableListItem.tsx
  src/components/group/anniversary/setting/DataPick.tsx
  src/components/group/anniversary/setting/SettingForm.tsx
  src/components/myfamily/TravelRecord.tsx
  src/types/types.ts
Labels: bugFix, api

#89 BUG : metadata image 보이도록 수정
  .env
  src/app/layout.tsx
  src/constants/metadata.ts
Labels: bugFix

#93 메인피드 전체공개 그룹공개 탭 추가
  src/app/Home.module.scss
  src/app/api/api.ts
  src/app/group/anniversary/page.tsx
  src/app/group/page.tsx
  src/app/myfamily/calendar/page.tsx
  src/app/myfamily/checklist/page.tsx
  src/app/myfamily/storage/[id]/travel-review/page.tsx
  src/app/myfamily/storage/page.tsx
  src/app/page.tsx
  src/components/group/profileImg.tsx
  src/components/main.module.scss
  src/components/mainClient.tsx
  src/styles/base/_globals.scss
  src/types/types.ts
Labels: feat, api

#108 리팩토링(서버액션 제거, 좋아요 기능 다듬기, Api.ts )
  .eslintrc.json
  public/svgs/heart-gray.svg
  src/app/api/api.ts
  src/app/api/fetchInstance.ts
  src/app/main/[id]/CommentLikeButton.tsx
  src/app/main/[id]/CommentSection.tsx
  src/app/main/[id]/LikeButton.tsx
  src/app/main/[id]/mainId.module.scss
  src/app/main/[id]/page.tsx
  src/components/main.module.scss
  src/components/mainClient.tsx
Labels: bugFix, refactor, api
