Repository SWYP-6-6/6-fe, pull requests merged in 2024-09, with the labels that each got.

#2 Sass 기본 설정 및 라이브러리 추가
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout.module.scss
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/base/_globals.scss
  src/styles/base/_normalize.scss
  src/styles/base/_reset.scss
  src/styles/base/common.scss
  src/styles/globals.scss
  src/styles/main.scss
  src/styles/mixins/_flexbox.scss
  src/styles/mixins/_image.scss
  src/styles/mixins/_position.scss
  src/styles/mixins/_responsive.scss
  src/styles/mixins/_scrollbar.scss
  src/styles/mixins/_text-style.scss
  src/styles/variables/_box-shadow.scss
  src/styles/variables/_breakpoint.scss
  src/styles/variables/_colors.scss
  src/styles/variables/_levels.scss
  src/styles/variables/_motions.scss
  src/styles/variables/_typography.scss
Labels: design, feat

#5 profile, invite 페이지 ui 및 폰트 추가
  public/font/Pretendard-Bold.otf
  public/font/Pretendard-Bold.woff
  public/font/Pretendard-Bold.woff2
  public/font/Pretendard-Regular.otf
  public/font/Pretendard-Regular.woff
  public/font/Pretendard-Regular.woff2
  public/svg/aniversary_icon.svg
  public/svg/camera_icon.svg
  public/svg/family_icon.svg
  public/svg/revise_icon.svg
  src/app/invite/InvitePage.module.scss
  src/app/invite/page.tsx
  src/app/profile/ProfilePage.module.scss
  src/app/profile/page.tsx
  src/styles/mixins/_text-style.scss
  src/styles/variables/_colors.scss
  src/styles/variables/_typography.scss
Labels: setting, design

#7 feat,UI: 닉네임 설정 페이지및 공용 활성화 비활성화 버튼 예시 생성
  src/app/_components/common/CommonButton.module.scss
  src/app/_components/common/CommonButton.tsx
  src/app/nicknamesetting/NicknamePage.module.scss
  src/app/nicknamesetting/page.tsx
Labels: design, feat

#8 Feat/hyun522/3
  .env
  public/svgs/kakao-icon.svg
  public/svgs/login-center.svg
  public/svgs/login-center4.svg
  src/app/not-found.tsx
  src/app/signin/page.tsx
  src/app/signin/signin.module.scss
Labels: design, feat

#13 메인페이지-게시글 작성 폼 UI 및 기능 구현
  .vscode/settings.json
  package-lock.json
  package.json
  public/fonts/Pretendard-Bold.otf
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-ExtraBold.otf
  public/fonts/Pretendard-ExtraBold.woff
  public/fonts/Pretendard-ExtraBold.woff2
  public/fonts/Pretendard-Light.otf
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.otf
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.otf
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.otf
  public/fonts/Pretendard-SemiBold.woff
  public/fonts/Pretendard-SemiBold.woff2
  public/svgs/aniversary_icon.svg
  public/svgs/camera.svg
  public/svgs/camera_icon.svg
  public/svgs/family_icon.svg
  public/svgs/return-button.svg
  public/svgs/revise_icon.svg
  src/app/mainform/MainFormPage.module.scss
  src/app/mainform/page.tsx
  src/app/profile/page.tsx
  src/app/signin/signin.module.scss
  src/styles/base/_reset.scss
  src/styles/mixins/_text-style.scss
  src/styles/variables/_colors.scss
  src/styles/variables/_typography.scss
Labels: design, feat

#17 profile,nicknamesetting ,group, myfamily, myfamily/calendar, 페이지 ui 완성 및 로딩화면 추가 스크롤 데이트피커 공용컴포넌트 추가
  package-lock.json
  package.json
  public/svgs/add-icon.svg
  public/svgs/dotmenu_icon.svg
  public/svgs/triangle_icon.svg
  src/_components/common/DatePicker.module.scss
  src/_components/common/DatePicker.tsx
  src/app/_components/myfamily/MainCalendar.scss
  src/app/_components/myfamily/MyFamily.module.scss
  src/app/_components/myfamily/MyFamily.tsx
  src/app/_components/nicknamesetting/NicknameForm.module.scss
  src/app/_components/nicknamesetting/NicknameForm.tsx
  src/app/_components/profile/ProfileToggles.module.scss
  src/app/_components/profile/ProfileToggles.tsx
  src/app/group/GroupPage.module.scss
  src/app/group/page.tsx
  src/app/invite/page.tsx
  src/app/loading.module.scss
  src/app/loading.tsx
  src/app/myfamily/calendar/Calendar.scss
  src/app/myfamily/calendar/CalendarPage.module.scss
  src/app/myfamily/calendar/page.tsx
  src/app/myfamily/layout.module.scss
  src/app/myfamily/layout.tsx
  src/app/myfamily/page.tsx
  src/app/nicknamesetting/NicknamePage.module.scss
  src/app/nicknamesetting/page.tsx
  src/app/profile/ProfilePage.module.scss
  src/app/profile/page.tsx
  src/styles/variables/_colors.scss
Labels: design, feat, refactor

#18 checklist 페이지 ui 구현 및 리팩토링
  src/_components/common/Header.tsx
  src/app/_components/myfamily/Calendar.module.scss
  src/app/_components/myfamily/Calendar.tsx
  src/app/_components/myfamily/Checklist.module.scss
  src/app/_components/myfamily/Checklist.tsx
  src/app/_components/myfamily/MainCalendar.scss
  src/app/_components/myfamily/MyFamily.module.scss
  src/app/_components/myfamily/MyFamily.tsx
  src/app/_components/myfamily/TravelRecord.module.scss
  src/app/_components/myfamily/TravelRecord.tsx
  src/app/_components/myfamily/Upcoming.module.scss
  src/app/_components/myfamily/Upcoming.tsx
  src/app/_components/nicknamesetting/NicknameForm.tsx
  src/app/myfamily/MyFamily.module.scss
  src/app/myfamily/calendar/CalendarPage.module.scss
  src/app/myfamily/calendar/page.tsx
  src/app/myfamily/checklist/CheckListPage.module.scss
  src/app/myfamily/checklist/page.tsx
  src/app/myfamily/page.tsx
Labels: design, feat, refactor

#20 메인피드 - 디테일 페이지 UI 작업
  src/_components/common/MainComment.module.scss
  src/_components/common/MainComment.tsx
  src/app/api/api.ts
  src/app/api/mainApi.ts
  src/app/main/[mainid]/mainId.module.scss
  src/app/main/[mainid]/page.tsx
  src/app/main/page.tsx
Labels: design, feat
